/**
 * Nonce utilities for CSP-compliant inline scripts and styles
 *
 * This module provides utilities for accessing the CSP nonce
 * generated by the middleware for use in server components.
 */

import { headers } from 'next/headers';

/**
 * Get the CSP nonce from the request headers
 * This nonce is generated by the middleware and should be used
 * for any inline scripts or styles that need to bypass CSP.
 *
 * @returns The nonce string, or undefined if not available
 *
 * @example
 * ```tsx
 * import { getNonce } from '@/lib/security/nonce';
 *
 * export default async function Page() {
 *   const nonce = await getNonce();
 *   return (
 *     <script nonce={nonce}>
 *       // Your inline script
 *     </script>
 *   );
 * }
 * ```
 */
export async function getNonce(): Promise<string | undefined> {
  try {
    const headersList = await headers();
    return headersList.get('x-nonce') ?? undefined;
  } catch {
    // Headers not available (e.g., during static generation)
    return undefined;
  }
}

/**
 * Generate a nonce for client-side use
 * This should only be used when server-side nonce is not available
 */
export function generateClientNonce(): string {
  if (typeof crypto !== 'undefined' && crypto.getRandomValues) {
    const array = new Uint8Array(16);
    crypto.getRandomValues(array);
    return btoa(String.fromCharCode(...array));
  }
  // Fallback for environments without crypto
  return Math.random().toString(36).substring(2, 18);
}
